### ISSUE TITLE
Npm Support?

### ISSUE THREAD

**Issue by isaac2004** [aspnet/LibraryInstaller#4]
Hey Mads,

Is there active work to add npm support? If not I might fork and take it on if there is a loose timeline

**Comment by madskristensen** [comment]
npm support is not something we want to add as a built-in provider. Instead a provider extension should be created. Here's a template of how to create extensions. I haven't written any docs on it yet though https://github.com/madskristensen/LibraryInstallerExtensionTemplate

That repo generates a "dotnet new" template that you can use to create the project. Simply start by executing `dotnet new --install LibraryInstallerExtensionTemplate::*` on the command line. That will create you the project. Then download [these NuGet packages](https://ci.appveyor.com/project/madskristensen/libraryinstaller/build/artifacts) into a local folder and add that folder as a new NuGet feed. Now you can open, restore and build the project in VS2017

**Comment by madskristensen** [comment]
I forgot to mention that you need the Visual Studio Extensibility workload installed. Simply add it from the VS installer if you haven't already

**Comment by spongessuck** [comment]
Would unpkg.com be a better candidate as a provider rather than NPM itself?

**Comment by madskristensen** [comment]
Yes, but it might be a combo dependent on their API
